In [38]:
import numpy as np


## first let's create the graph manually
w1 = ('A', ('B','C','D'))
w2 = ('B', ('A','D'))
w3 = ('C',('A'))
w4 = ('D',('B','C'))

#Graph
G = [w1,w2,w3,w4]
print(G)


# create page rank vector and initialize it

page_rank = []
for i in range(len(G)):
    page_rank.append(1/len(G))

page_rank = np.array(page_rank)
print(page_rank)


# Create Transition matrix, but we would need some sort of index or numbers for 'A', 'B' etc

alpha_index = {}

alpha_index['A'] = 0
alpha_index['B'] = 1
alpha_index['C'] = 2
alpha_index['D'] = 3

## OK

M = []
for node in G:
    print(node)
    single_row = np.zeros(len(G))
    single_row[alpha_index[node[0]]] = 0
    wt = len(node[1])
    for x in node[1]:
        single_row[alpha_index[x]] = (1.0/wt)
    M.append(single_row)

M = np.array(M)
print("\n\n\n")
print(M)
print()
print("Need to take transpose of this matrix to fit the notion of the MMDS book")
print("\n")
M = np.transpose(M)
print(M)


error = np.inf
i = 1
while(error >= 0.0000001):
    i=i+1  ## to print iterations
    page_rank_new = np.matmul(M,page_rank)
#     print(page_rank)
#     print()
#     print(page_rank_new)
    error = np.linalg.norm(page_rank - page_rank_new)
#     print(error)
    page_rank = page_rank_new

print("Sweet !!")
print("Number of iterations took:{}",i)
print(page_rank)
    






[('A', ('B', 'C', 'D')), ('B', ('A', 'D')), ('C', 'A'), ('D', ('B', 'C'))]
[ 0.25  0.25  0.25  0.25]
('A', ('B', 'C', 'D'))
('B', ('A', 'D'))
('C', 'A')
('D', ('B', 'C'))




[[ 0.          0.33333333  0.33333333  0.33333333]
 [ 0.5         0.          0.          0.5       ]
 [ 1.          0.          0.          0.        ]
 [ 0.          0.5         0.5         0.        ]]

Need to take transpose of this matrix to fit the notion of the MMDS book


[[ 0.          0.5         1.          0.        ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.5         0.          0.        ]]
Sweet !!
Number of iterations took:{} 23
[ 0.33333331  0.22222223  0.22222223  0.22222223]
